import React from 'react';
import { MDBDataTableV5, MDBBtn } from 'mdbreact';
import { MDBCardTitle } from 'mdb-react-ui-kit';

export default function TopSearchSelect() {
  const [datatable, setDatatable] = React.useState({
    columns: [
        {
            label: 'RFI',
            field: 'rfi',
            width: 270,
        },
        {
          label: 'Name',
          field: 'name',
          width: 150,
          attributes: {
            'aria-controls': 'DataTable',
            'aria-label': 'Name',
          },
        },
      {
        label: 'RFI Type',
        field: 'rfiType',
        width: 270,
      },
      {
        label: 'Location',
        field: 'office',
        width: 200,
      },
      {
        label: 'Material Ready Date',
        field: 'date',
        sort: 'disabled',
        width: 150,
      },
      {
        label: 'Material Cost',
        field: 'salary',
        sort: 'disabled',
        width: 100,
      },
    ],
    rows: [
      {
        name: 'Tiger Nixon',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '61',
        date: '2011/04/25',
        salary: '$320,000',
      },
      {
        name: 'Garrett Winters',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Tokyo',
        age: '63',
        date: '2011/07/25',
        salary: '$170,000',
      },
      {
        name: 'Ashton Cox',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '66',
        date: '2009/01/12',
        salary: '$86,000',
      },
      {
        name: 'Cedric Kelly',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '22',
        date: '2012/03/29',
        salary: '$433,000',
      },
      {
        name: 'Airi Satou',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Tokyo',
        age: '33',
        date: '2008/11/28',
        salary: '$162,000',
      },
      {
        name: 'Brielle Williamson',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '61',
        date: '2012/12/02',
        salary: '$372,000',
      },
      {
        name: 'Herrod Chandler',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '59',
        date: '2012/08/06',
        salary: '$137,000',
      },
      {
        name: 'Rhona Davidson',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Tokyo',
        age: '55',
        date: '2010/10/14',
        salary: '$327,000',
      },
      {
        name: 'Colleen Hurst',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '39',
        date: '2009/09/15',
        salary: '$205,000',
      },
      {
        name: 'Sonya Frost',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '23',
        date: '2008/12/13',
        salary: '$103,000',
      },
      {
        name: 'Jena Gaines',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '30',
        date: '2008/12/19',
        salary: '$90,000',
      },
      {
        name: 'Quinn Flynn',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '22',
        date: '2013/03/03',
        salary: '$342,000',
      },
      {
        name: 'Charde Marshall',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '36',
        date: '2008/10/16',
        salary: '$470,000',
      },
      {
        name: 'Haley Kennedy',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '43',
        date: '2012/12/18',
        salary: '$313,000',
      },
      {
        name: 'Tatyana Fitzpatrick',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '19',
        date: '2010/03/17',
        salary: '$385,000',
      },
      {
        name: 'Michael Silva',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '66',
        date: '2012/11/27',
        salary: '$198,000',
      },
      {
        name: 'Paul Byrd',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '64',
        date: '2010/06/09',
        salary: '$725,000',
      },
      {
        name: 'Gloria Little',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '59',
        date: '2009/04/10',
        salary: '$237,000',
      },
      {
        name: 'Bradley Greer',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '41',
        date: '2012/10/13',
        salary: '$132,000',
      },
      {
        name: 'Dai Rios',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '35',
        date: '2012/09/26',
        salary: '$217,000',
      },
      {
        name: 'Jenette Caldwell',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '30',
        date: '2011/09/03',
        salary: '$345,000',
      },
      {
        name: 'Yuri Berry',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '40',
        date: '2009/06/25',
        salary: '$675,000',
      },
      {
        name: 'Caesar Vance',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '21',
        date: '2011/12/12',
        salary: '$106,000',
      },
      {
        name: 'Doris Wilder',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Sidney',
        age: '23',
        date: '2010/09/20',
        salary: '$85,000',
      },
      {
        name: 'Angelica Ramos',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '47',
        date: '2009/10/09',
        salary: '$1,000',
      },
      {
        name: 'Gavin Joyce',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '42',
        date: '2010/12/22',
        salary: '$92,000',
      },
      {
        name: 'Jennifer Chang',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Singapore',
        age: '28',
        date: '2010/11/14',
        salary: '$357,000',
      },
      {
        name: 'Brenden Wagner',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '28',
        date: '2011/06/07',
        salary: '$206,000',
      },
      {
        name: 'Fiona Green',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '48',
        date: '2010/03/11',
        salary: '$850,000',
      },
      {
        name: 'Shou Itou',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Tokyo',
        age: '20',
        date: '2011/08/14',
        salary: '$163,000',
      },
      {
        name: 'Michelle House',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Sidney',
        age: '37',
        date: '2011/06/02',
        salary: '$95,000',
      },
      {
        name: 'Suki Burks',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '53',
        date: '2009/10/22',
        salary: '$114,000',
      },
      {
        name: 'Prescott Bartlett',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '27',
        date: '2011/05/07',
        salary: '$145,000',
      },
      {
        name: 'Gavin Cortez',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '22',
        date: '2008/10/26',
        salary: '$235,000',
      },
      {
        name: 'Martena Mccray',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '46',
        date: '2011/03/09',
        salary: '$324,000',
      },
      {
        name: 'Unity Butler',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '47',
        date: '2009/12/09',
        salary: '$85,000',
      },
      {
        name: 'Howard Hatfield',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '51',
        date: '2008/12/16',
        salary: '$164,000',
      },
      {
        name: 'Hope Fuentes',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '41',
        date: '2010/02/12',
        salary: '$109,000',
      },
      {
        name: 'Vivian Harrell',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '62',
        date: '2009/02/14',
        salary: '$452,000',
      },
      {
        name: 'Timothy Mooney',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '37',
        date: '2008/12/11',
        salary: '$136,000',
      },
      {
        name: 'Jackson Bradshaw',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '65',
        date: '2008/09/26',
        salary: '$645,000',
      },
      {
        name: 'Olivia Liang',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Singapore',
        age: '64',
        date: '2011/02/03',
        salary: '$234,000',
      },
      {
        name: 'Bruno Nash',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '38',
        date: '2011/05/03',
        salary: '$163,000',
      },
      {
        name: 'Sakura Yamamoto',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Tokyo',
        age: '37',
        date: '2009/08/19',
        salary: '$139,000',
      },
      {
        name: 'Thor Walton',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '61',
        date: '2013/08/11',
        salary: '$98,000',
      },
      {
        name: 'Finn Camacho',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '47',
        date: '2009/07/07',
        salary: '$87,000',
      },
      {
        name: 'Serge Baldwin',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Singapore',
        age: '64',
        date: '2012/04/09',
        salary: '$138,000',
      },
      {
        name: 'Zenaida Frank',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '63',
        date: '2010/01/04',
        salary: '$125,000',
      },
      {
        name: 'Zorita Serrano',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '56',
        date: '2012/06/01',
        salary: '$115,000',
      },
      {
        name: 'Jennifer Acosta',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '43',
        date: '2013/02/01',
        salary: '$75,000',
      },
      {
        name: 'Cara Stevens',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '46',
        date: '2011/12/06',
        salary: '$145,000',
      },
      {
        name: 'Hermione Butler',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '47',
        date: '2011/03/21',
        salary: '$356,000',
      },
      {
        name: 'Lael Greer',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'London',
        age: '21',
        date: '2009/02/27',
        salary: '$103,000',
      },
      {
        name: 'Jonas Alexander',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'San Francisco',
        age: '30',
        date: '2010/07/14',
        salary: '$86,000',
      },
      {
        name: 'Shad Decker',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Edinburgh',
        age: '51',
        date: '2008/11/13',
        salary: '$183,000',
      },
      {
        name: 'Michael Bruce',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'Singapore',
        age: '29',
        date: '2011/06/27',
        salary: '$183,000',
      },
      {
        name: 'Donna Snider',
        rfi: 'PO1839-01',
        rfiType: 'Special Project',
        office: 'New York',
        age: '27',
        date: '2011/01/25',
        salary: '$112,000',
      },
    ],
  });

  return (
    <div>
      <MDBDataTableV5
        hover
        entriesOptions={[5, 20, 25]}
        entries={5}
        pagesAmount={4}
        data={datatable}
        searchTop
        searchBottom={false}
      />
    </div>
  );
}
